Blocks and styles Heading 1-5 added
Slava324/superhero-shop pull request #1
Opened 2022-05-19 21:15 UTC by xAsparax

Верстка блоків "заголовки" проєкту "[Магазин Супергероїв](https://www.figma.com/community/file/1094015754993438424)":

- Назва блоку - headingX де X розмір заголовку. 1 найбільший 5 найменший
- Розміри шрифту для заголовку 4 і 5 - 16px та 14px відповідно
-
![photo1652903164](https://user-images.githubusercontent.com/102807093/169405786-c049cc93-a92b-4028-bf09-c23597140dd9.jpeg)

2022-05-20 20:12 UTC, Slava324 requested changes

2022-05-20 20:12 UTC, Slava324 commented on style.css
> +  font-weight: 600;
так само як і по шрифтах. думаю зараз не потрібно вказувати font-weight. це стосується і інших блоків

2022-05-20 21:37 UTC, xAsparax commented on style.css
> +.heading1 h1{
Ок

2022-05-20 21:38 UTC, xAsparax commented on tech/tech.html
>      <div class="tech__content">
Не помітила, виправлю. (але в мене в браузері відображаються блоки)

2022-05-20 21:39 UTC, xAsparax commented on style.css
> +  font-family: 'Roboto', sans-serif;
Згодна, добавила для наглядності.

2022-05-20 21:55 UTC, xAsparax commented on style.css
> +  font-stretch: condensed;
Я вважаю, що heading  відповідає за розмір і стиль (вага, жирність чи як це назвати). В макеті у заголовків h1, h2 і т.д. (крім третього) вказаний стиль condensed medium (тільки третій заголовок - bold). Оскільки для css такого значення немає (condensed medium), я взяла його параметри з макету, див. доданий скрін. Вага 500 в браузері не відмальовується, 600 відповідає візуально шрифту в макеті. Тобто ціль була отримати шріфт візуально такий самий як в макеті. Якщо не додавати вагу та stretch, написання заголовку буде як у звичайному тексті. https://thumbsnap.com/5XTd7KP5

2022-05-20 21:57 UTC, xAsparax commented on style.css
> +  font-weight: 600;
Я можу залишити лише розмір, у стилі, але тоді заголовок виглядатиме як звичайний текст, тобто не відрізнятиметься за жирністю.

2022-05-21 16:45 UTC, Slava324 requested changes

2022-05-21 16:45 UTC, Slava324 commented on style.css
> +.heading2 h2{
В мене ще є коментар по регістру літер. Здається всі заголовки H2 в макеті пишуться великими літерами.

2022-05-21 16:45 UTC, Slava324 commented on style.css
> +.heading1 h1{
У всіх заголовків також є line-height.

2022-05-21 16:45 UTC, Slava324 commented on style.css
> +.heading1 h1{
Також у заголовків є колір.

2022-05-21 16:45 UTC, Slava324 commented on style.css
> +.heading1 h1{
В макеті заголовок H1 є у двох варіантах. Один варіант з тінню. Можливо додати модифікатор і зробити також з тінню?

2022-05-21 16:45 UTC, Slava324 commented on style.css
> +  font-weight: 600;
Так дійсно думаю жирність треба залишити. Але. Я трохи не зрозумів Вашого коментаря той що нижче про жирність. Як я розумію. Шрифти коли підключаються, там відразу і жирність обирається, тому жирність я б ставив як в макеті. Якщо вказано 500 у заголовка, то має бути 500. І коли ми підключимо шрифти з жирністю 500 то жирність буде 500.

2022-05-21 16:45 UTC, Slava324 commented on style.css
> +  font-stretch: condensed;
Я вище на цей комент відповів. Я стилі дивлюся на вкладці Inspect в Figma. Там вказано жирність 500 і нема такого значення як font-stretch: condensed. 
![image](https://user-images.githubusercontent.com/60036424/169661287-52a8af50-9737-42b7-a71f-89c07d78856a.png)

2022-05-21 18:30 UTC, xAsparax commented
Щодо ваги 500, так, я підв"язала шрифти звідси https://fonts.google.com/specimenTab?standard-styles#standard-styles (всі стилі), і 500 стало відображатися потрібної жирності. Але стилю condensed  там немає. А у властивостях заголовку в фігмі він є (см. зображення https://thumbsnap.com/UZVBkS9k ). (хоча і немає в inspect) Якщо його не вказати, то шрифт виходить більш розтягнутий, ніж в макеті (тобто просто medium, а треба трошки більше зжатий з боків). Єдиний спосіб, який я знайшла, щоб отримати відповідність до макету - це команда font-stretch: condensed; (https://www.w3.org/Style/Examples/007/fonts.ru.html)
Але інша проблема, після того, як я підключила шрифти через input, команда font-stretch: condensed; перестала працювати...

2022-05-21 18:45 UTC, xAsparax commented
Попереднє посилання на шрифти поламалося( https://fonts.google.com/specimen/Roboto

2022-05-22 16:26 UTC, merged